"""empty message

Revision ID: 665d0df06bec
Revises: 
Create Date: 2024-01-11 22:00:46.902815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '665d0df06bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('interventions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('wording', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('speaker', sa.String(), nullable=True),
                    sa.Column('location', sa.String(), nullable=True),
                    sa.Column('date_of_intervention', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### commands auto generated by Alembic - please adjust! ###
    status_type = postgresql.ENUM('Draft', 'Validated', 'Completed', name='intervention_status')
    status_type.create(op.get_bind())
    op.add_column('interventions', sa.Column('status', status_type, server_default='Draft', nullable=False))


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'status')
    status_type = postgresql.ENUM('Draft', 'Validated', 'Completed', name='intervention_status')
    status_type.drop(op.get_bind())
    # ### end Alembic commands ###
